<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Contains base_layouts.module.
 */

/**
 *
 */
function layouts_custom_form_layout_builder_configure_section_alter(&$form, FormStateInterface $form_state, $form_id) {
  $formObject = $form_state->getFormObject();
  $layout = $formObject->getCurrentLayout();
  $config = $layout->getConfiguration();

  $options_margin_top = [
    '' => t('Seleccione'),
    'mt-0' => t('Ninguno'),
    'mt-1' => t('S'),
    'mt-2' => t('M'),
    'mt-3' => t('L'),
  ];

  $options_margin_bottom = [
    '' => t('Seleccione'),
    'mb-0' => t('Ninguno'),
    'mb-1' => t('S'),
    'mb-2' => t('M'),
    'mb-3' => t('L'),
  ];

  $options_left_right = [
    '' => t('Seleccione'),
    'mx-0' => t('Ninguno'),
    'mx-1' => t('S'),
    'mx-2' => t('M'),
    'mx-3' => t('L'),
  ];

  $options_padding_top = [
    '' => t('Seleccione'),
    'pt-0' => t('Ninguno'),
    'pt-1' => t('S'),
    'pt-2' => t('M'),
    'pt-3' => t('L'),
  ];

  $options_padding_bottom = [
    '' => t('Seleccione'),
    'pb-0' => t('Ninguno'),
    'pb-1' => t('S'),
    'pb-2' => t('M'),
    'pb-3' => t('L'),
  ];

  $options_padding_left_right = [
    '' => t('Seleccione'),
    'py-0' => t('Ninguno'),
    'px-1' => t('S'),
    'px-2' => t('M'),
    'px-3' => t('L'),
  ];

  $form['margin_settings'] = [
    '#type' => 'details',
    '#title' => t('Margen'),
    '#weight' => -1,
  ];

  $form['margin_settings']['margin_top'] = [
    '#type' => 'select',
    '#title' => t('Superior'),
    '#options' => $options_margin_top,
    '#default_value' => $config['margin_settings']['margin_top'] ?? '',
  ];

  $form['margin_settings']['margin_bottom'] = [
    '#type' => 'select',
    '#title' => t('Inferior'),
    '#options' => $options_margin_bottom,
    '#default_value' => $config['margin_settings']['margin_bottom'] ?? '',
  ];

  $form['margin_settings']['margin_left_right'] = [
    '#type' => 'select',
    '#title' => t('Izquierda - Derecha'),
    '#options' => $options_left_right,
    '#default_value' => $config['margin_settings']['margin_left_right'] ?? '',
  ];

  $form['padding_settings'] = [
    '#type' => 'details',
    '#title' => t('Relleno'),
    '#weight' => -1,
  ];

  $form['padding_settings']['padding_top'] = [
    '#type' => 'select',
    '#title' => t('Superior'),
    '#options' => $options_padding_top,
    '#default_value' => $config['padding_settings']['padding_top'] ?? '',
  ];

  $form['padding_settings']['padding_bottom'] = [
    '#type' => 'select',
    '#title' => t('Inferior'),
    '#options' => $options_padding_bottom,
    '#default_value' => $config['padding_settings']['padding_bottom'] ?? '',
  ];

  $form['padding_settings']['padding_left_right'] = [
    '#type' => 'select',
    '#title' => t('Izquierda - Derecha'),
    '#options' => $options_padding_left_right,
    '#default_value' => $config['padding_settings']['padding_left_right'] ?? '',
  ];

  $form['style_settings'] = [
    '#type' => 'details',
    '#title' => t('Estilos'),
    '#weight' => -1,
  ];

  $form['style_settings']['classes_custom'] = [
    '#type' => 'textfield',
    '#title' => t('Clase'),
    '#default_value' => $config['style_settings']['classes_custom'] ?? '',
  ];

  $form['style_settings']['id'] = [
    '#type' => 'textfield',
    '#title' => t('ID'),
    '#default_value' => $config['style_settings']['id'] ?? '',
  ];

  array_unshift($form['#submit'], '_layout_custom_submit_form');
}

/**
 *
 */
function _layout_custom_submit_form(array &$form, FormStateInterface $form_state) {
  $formObject = $form_state->getFormObject();
  $config = $formObject->getCurrentLayout()->getConfiguration();
  $margin_settings = $form_state->getValue(['margin_settings']);
  $padding_settings = $form_state->getValue(['padding_settings']);
  $style_settings = $form_state->getValue(['style_settings']);
  $config['margin_settings'] = $margin_settings;
  $config['padding_settings'] = $padding_settings;
  $config['style_settings'] = $style_settings;
  $formObject->getCurrentLayout()->setConfiguration($config);
}

/**
 *
 */
function layouts_custom_preprocess_layout(&$variables) {
  $margin_settings = $variables["settings"]["margin_settings"] ?? '';
  if ($margin_settings) {
    foreach ($margin_settings as $ms) {
      $variables["attributes"]["class"][] = $ms;
    }
  }

  $padding_settings = $variables["settings"]["padding_settings"] ?? '';
  if ($padding_settings) {
    foreach ($padding_settings as $ps) {
      $variables["attributes"]["class"][] = $ps;
    }
  }

  $classes_custom = $variables["settings"]["style_settings"]["classes_custom"] ?? '';
  if ($classes_custom) {
    $variables["attributes"]["class"][] = $classes_custom;
  }

  $id_custom = $variables["settings"]["style_settings"]["id"] ?? '';
  if ($id_custom) {
    $variables["attributes"]["id"][] = $id_custom;
  }

}
