<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Contains base_layouts.module.
 */

/**
 *
 */
function layouts_custom_form_layout_builder_configure_section_alter(&$form, FormStateInterface $form_state, $form_id) {
  $formObject = $form_state->getFormObject();
  $layout = $formObject->getCurrentLayout();
  $config = $layout->getConfiguration();

  $options_margin_top = [
    '' => t('Seleccione'),
    'mt-0' => t('Ninguno'),
    'mt-1' => t('S'),
    'mt-2' => t('M'),
    'mt-3' => t('L'),
  ];

  $options_margin_bottom = [
    '' => t('Seleccione'),
    'mb-0' => t('Ninguno'),
    'mb-1' => t('S'),
    'mb-2' => t('M'),
    'mb-3' => t('L'),
  ];

  $options_left_right = [
    '' => t('Seleccione'),
    'mx-0' => t('Ninguno'),
    'mx-1' => t('S'),
    'mx-2' => t('M'),
    'mx-3' => t('L'),
  ];

  $form['margin_settings'] = [
    '#type' => 'details',
    '#title' => t('Margen'),
    '#weight' => 0,
  ];

  $form['margin_settings']['margin_top'] = [
    '#type' => 'select',
    '#title' => t('Superior'),
    '#options' => $options_margin_top,
    '#default_value' => $config['margin_settings']['margin_top'] ?? '',
  ];

  $form['margin_settings']['margin_bottom'] = [
    '#type' => 'select',
    '#title' => t('Inferior'),
    '#options' => $options_margin_bottom,
    '#default_value' => $config['margin_settings']['margin_bottom'] ?? '',
  ];

  $form['margin_settings']['margin_left_right'] = [
    '#type' => 'select',
    '#title' => t('Izquierda - Derecha'),
    '#options' => $options_left_right,
    '#default_value' => $config['margin_settings']['margin_left_right'] ?? '',
  ];

  array_unshift($form['#submit'], '_layout_custom_submit_form');
}

/**
 *
 */
function _layout_custom_submit_form(array &$form, FormStateInterface $form_state) {
  $formObject = $form_state->getFormObject();
  $config = $formObject->getCurrentLayout()->getConfiguration();
  $margin_settings = $form_state->getValue(['margin_settings']);
  $config['margin_settings'] = $margin_settings;
  $formObject->getCurrentLayout()->setConfiguration($config);
}

/**
 *
 */
function layouts_custom_preprocess_layout(&$variables) {

  $margin_settings = $variables["settings"]["margin_settings"] ?? '';
  foreach ($margin_settings as $ms) {
    $variables["attributes"]["class"][] = $ms;
  }

}
